name: fwhleng
channels:
  - defaults
dependencies:
  - matplotlib=3.7
  - numpy=1.24
  - pandas=1.5
  - pymongo=4.3.3
  - requests=2.28
  - python-dotenv=1.0
  - alive-progress=3.1
  - scikit-learn=1.2
  - statsmodels=0.13
  - hyperopt=0.2.7
  - mlflow=1.26
  - azureml-mlflow=1.50
  - azureml-core=1.51
  - xgboost=1.7
  - seaborn=0.12
  - pytest=7.2
  - codecov=2.1
  - plotly=5.13
  - torch=2.0
  - hydra-core=1.3
  - pip:
    - docopt-ng=0.8
    - pyarrow=9.0
