name: fwhleng
dependencies:
  - python=3.10
  - ipykernel=6.22
  - matplotlib=3.7
  - pandas=1.5
  - pymongo=4.3.3
  - requests=2.28
  - plotly=5.13
  - numpy=1.24
  - python-dotenv=1.0
  - alive-progress=3.1
  - jinja2=3.1
  - pip=23.0
  - pip:
    - docopt-ng~=0.8

